name: CI build & push & update-manifests

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  IMAGE_NAME: hello-app
  DOCKERHUB_NAMESPACE: ksmin0306           # Docker Hub 닉네임
  TAG_SHA: ${{ github.sha }}
  MANIFESTS_REPO: cong-0306/k8s-manifests  # 매니페스트는 GitHub(cong-0306) 그대로
  MANIFESTS_PATH: hello-app
  MANIFESTS_BRANCH: main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout app repo
        uses: actions/checkout@v4

      - name: Set short SHA
        id: vars
        run: echo "short_sha=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}   # = ksmin0306
          password: ${{ secrets.DOCKERHUB_TOKEN }}      # Docker Hub Access Token

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.DOCKERHUB_NAMESPACE }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.DOCKERHUB_NAMESPACE }}/${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.short_sha }}
          build-args: |
            APP_VERSION=${{ steps.vars.outputs.short_sha }}

  update-manifests:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout manifests repo
        uses: actions/checkout@v4
        with:
          repository: ${{ env.MANIFESTS_REPO }}          # cong-0306/k8s-manifests
          token: ${{ secrets.MANIFESTS_REPO_TOKEN }}     # PAT(repo 권한)
          ref: ${{ env.MANIFESTS_BRANCH }}

      - name: Update Deployment image tag
        working-directory: ${{ env.MANIFESTS_PATH }}
        run: |
          short_sha=${GITHUB_SHA::7}
          image="${{ env.DOCKERHUB_NAMESPACE }}/${{ env.IMAGE_NAME }}"
          # deployment.yaml 의 이미지 태그를 짧은 SHA로 치환
          sed -i -E "s#(${image}):[a-zA-Z0-9._-]+#\1:${short_sha}#g" deployment.yaml

      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "CI: update ${IMAGE_NAME} image tag to ${GITHUB_SHA::7}" || echo "No changes"
          git push origin ${{ env.MANIFESTS_BRANCH }}
